// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Volt.Infrastructure.Data;

#nullable disable

namespace Volt.Infrastructure.Migrations;

[DbContext(typeof(DataContext))]
[Migration("20260714150000_SolarInverterCatalogSeedFix")]
partial class SolarInverterCatalogSeedFix
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // This migration only repairs catalog seed data; the model is unchanged.
    }
}
