// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Volt.Infrastructure.Data;

#nullable disable

namespace Volt.Infrastructure.Migrations;

[DbContext(typeof(DataContext))]
[Migration("20260714160000_SolarInverterPhaseRepair")]
partial class SolarInverterPhaseRepair
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // This migration only repairs normalized catalog values; the model is unchanged.
    }
}
